version: '3'
services:
  flaskperf:
    build: ./flaskPerf
    container_name: flaskperf
    environment:
      - PYTHONUNBUFFERED=True                   
    restart: on-failure
    volumes:
      - ./flaskPerf:/flaskPerf
    ports:
      - "5000:5000"
    command: python start.py
  
  influxdb2:
    image: influxdb:2.0
    container_name: influxdb2
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    ports:
      - "8086:8086"
    expose:
      - 8086
    restart: always
  grafana:
      image: grafana/grafana-oss:8.3.6
      hostname: grafana
      container_name: grafana
      user: "472"
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=Password1
        - GF_SECURITY_ADMIN_USER=admin
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_INSTALL_PLUGINS=cloudspout-button-panel
        - GF_RENDERING_SERVER_URL=http://renderer:8081/render
        - GF_RENDERING_CALLBACK_URL=http://grafana:3000/          
      volumes:
        - grafana-home:/var/lib/grafana/
        - grafana-conf:/etc/grafana/      
      restart: always
  renderer:
     image: grafana/grafana-image-renderer:latest
     ports:
       - 8081
volumes:
   influxdb2-data:
   influxdb2-config:
   grafana-home:
   grafana-conf: