{
 "title": "Main dashboard",
 "description": "JMeter dashboard for Influxdb2 datasource",
 "tags": [
  "main",
  "sitecore"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "agr", "label": "Aggregation", "query": "1,10,60,1800,3600" },
   {
    "name": "testProfile",
    "label": "testProfile",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n  bucket: v.bucket,\r\n  measurement: \"tests\",\r\n  tag: \"testProfile\"\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Test log",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\n\r\ndata = from(bucket: \"jmeter\")\r\n  |> range(start: 0, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"samples\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"threads\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"testId\", \"testProfile\"])\r\n  |> group(columns: [\"testId\", \"testProfile\"])\r\n\r\nmaxThreads = data \r\n  |> max(column: \"_value\")\r\n  |> keep(columns: [\"_value\", \"testId\", \"testProfile\"])\r\n  |> group(columns: [\"_value\", \"testId\", \"testProfile\"])\r\n  |> rename(columns: {_value: \"maxThreads\"})\r\n\r\nendTime = data \r\n  |> max(column: \"_time\")\r\n  |> keep(columns: [\"_time\", \"testId\", \"testProfile\"])\r\n  |> group(columns: [\"_time\", \"testId\", \"testProfile\"])\r\n  |> rename(columns: {_time: \"endTime\"})\r\n\r\nstartTime = data \r\n  |> min(column: \"_time\")\r\n  |> keep(columns: [\"_time\", \"testId\", \"testProfile\"])\r\n  |> group(columns: [\"_time\", \"testId\", \"testProfile\"])\r\n  |> rename(columns: {_time: \"startTime\"})\r\n\r\njoin1 = join(tables: {d1: maxThreads, d2: startTime}, on: [\"testId\", \"testProfile\"])\r\n  |> keep(columns: [\"startTime\",\"testId\", \"testProfile\",  \"maxThreads\"])\r\n  |> group(columns: [\"testId\", \"testProfile\"])\r\n\r\njoin(tables: {d1: join1, d2: endTime}, on: [\"testId\", \"testProfile\"])\r\n  |> map(fn: (r) => ({ r with duration: (int(v: r.endTime) - int(v: r.startTime))}))\r\n  |> map(fn: (r) => ({ r with dashboard: strings.joinStr(arr: [\r\n      \"<a href=\\\"d/jmeter-test-results/jmeter-test-results?orgId=1&from=\",\r\n      string(v: int(v: r.startTime)/1000000),\"&to=\",\r\n      string(v: int(v: r.endTime)/1000000),\"&var-aggregation=60&var-sampleType=transaction&var-testId=\",  \r\n      string(v: r.testId),\"&var-testProfile=\",string(v: r.testProfile),\"\\\">Dashboard</a>\"\r\n      ], \r\n      v: \"\") }))\r\n  |> keep(columns: [\"startTime\",\"testId\", \"testProfile\",  \"maxThreads\", \"duration\", \"dashboard\"])\r\n  |> group(columns: [\"1\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": " from(bucket: v.bucket)\r\n  |> range(start: 0, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tests\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"avg_tr\")\r\n  |> filter(fn: (r) => r[\"testProfile\"] == \"${testProfile}\") \r\n  |> toFloat() \r\n  |> keep(columns: [\"testId\", \"_value\"])\r\n  |> group()\r\n"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 18, "w": 3, "x": 21, "y": 0 } },
  {
   "title": "Median response time",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": " from(bucket: v.bucket)\r\n  |> range(start: 0, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tests\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"median_tr\")\r\n  |> filter(fn: (r) => r[\"testProfile\"] == \"${testProfile}\") \r\n  |> toFloat() \r\n  |> keep(columns: [\"testId\", \"_value\"])\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Baselines",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"jmeter\")\r\n  |> range(start: 0, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tests\")\r\n  |> map(fn:(r) => ({ r with startTime: int(v: r.startTime) }))\r\n  |> group(columns: [\"testProfile\"])\r\n  |> max(column: \"startTime\")\r\n  |> group()\r\n  |> map(fn: (r) => ({ r with dashboard: strings.joinStr(arr: [\r\n      \"<a href=\\\"d/jmeter-test-results/jmeter-test-results?orgId=1&from=\",\r\n      string(v: int(v: r.startTime)),\"&to=\",\r\n      string(v: int(v: r.endTime)),\"&var-aggregation=60&var-sampleType=transaction&var-testId=\",\r\n      string(v: r.testId),\"&var-testProfile=\",string(v: r.testProfile),\"\\\">Dashboard</a>\"\r\n      ], \r\n      v: \"\") }))\r\n  |> keep(columns: [\"testId\", \"testProfile\", \"dashboard\", \"rfc\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}