{
 "title": "Main dashboard",
 "description": "JMeter dashboard for ClickHouse datasource",
 "tags": [
  "main",
  "sitecore"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testName",
    "label": "testName",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.bucket, \r\n  tag: \"testName\",\r\n  start: -1000d\r\n)"
   },
   {
    "name": "testType",
    "label": "testType",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.bucket, \r\n  tag: \"testType\",\r\n  start: -1000d\r\n)"
   },
   { "name": "InfluxdbDataSource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Test log ",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\n\r\ndata = from(bucket: v.bucket)\r\n  |> range(start: 0, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"virtualUsers\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"maxActiveThreads\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"runId\", \"testName\", \"testType\"])\r\n  |> group(columns: [\"runId\", \"testName\"])\r\n  |> fill(column: \"testType\", value: \"-\")\r\n\r\nmaxThreads = data \r\n  |> max(column: \"_value\")\r\n  |> keep(columns: [\"_value\", \"runId\", \"testName\", \"testType\"])\r\n  |> group(columns: [\"_value\", \"runId\", \"testName\"])\r\n  |> rename(columns: {_value: \"maxThreads\"})\r\n\r\nendTime = data \r\n  |> max(column: \"_time\")\r\n  |> keep(columns: [\"_time\", \"runId\", \"testName\", \"testType\"])\r\n  |> group(columns: [\"_time\", \"runId\", \"testName\"])\r\n  |> rename(columns: {_time: \"endTime\"})\r\n\r\nstartTime = data \r\n  |> min(column: \"_time\")\r\n  |> keep(columns: [\"_time\", \"runId\", \"testName\", \"testType\"])\r\n  |> group(columns: [\"_time\", \"runId\", \"testName\"])\r\n  |> rename(columns: {_time: \"startTime\"})\r\n\r\njoin1 = join(tables: {d1: maxThreads, d2: startTime}, on: [\"runId\", \"testName\", \"testType\"])\r\n  |> keep(columns: [\"startTime\",\"runId\", \"testName\",  \"maxThreads\", \"testType\"])\r\n  |> group(columns: [\"runId\", \"testName\"])\r\n\r\njoin(tables: {d1: join1, d2: endTime}, on: [\"runId\", \"testName\", \"testType\"])\r\n  |> map(fn: (r) => ({ r with duration: (int(v: r.endTime) - int(v: r.startTime))}))\r\n  |> map(fn: (r) => ({ r with dashboard: strings.joinStr(arr: [\r\n      \"<a href=\\\"d/jmeter-results/jmeter-test-results?orgId=1&from=\",\r\n      string(v: int(v: r.startTime)/1000000),\"&to=\",\r\n      string(v: int(v: r.endTime)/1000000),\"&var-aggregation=60&var-sampleType=transaction&var-runId=\",  \r\n      string(v: r.runId),\"&var-testName=\",string(v: r.testName),\"\\\">Dashboard</a>\"\r\n      ], \r\n      v: \"\") }))\r\n  |> map(fn: (r) => ({ r with compare: strings.joinStr(arr: [\r\n      \"<a href=\\\"d/jmeter-comp/jmeter-load-test-comparison?orgId=1&from=\",\r\n      string(v: int(v: r.startTime)/1000000),\"&to=\",\r\n      string(v: int(v: r.endTime)/1000000),\"&var-sampleType=transaction&var-current_runId=\",  \r\n      string(v: r.runId),\"&var-testName=\",string(v: r.testName),\"\\\">Compare</a>\"\r\n      ], \r\n      v: \"\") }))\r\n  |> keep(columns: [\"startTime\",\"runId\", \"testName\",  \"maxThreads\", \"duration\", \"dashboard\", \"compare\", \"testType\"])\r\n  |> group(columns: [\"1\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Baselines",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: 0, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tests\")\r\n  |> map(fn:(r) => ({ r with startTime: int(v: r.startTime) }))\r\n  |> group(columns: [\"testName\", \"testType\"])\r\n  |> max(column: \"startTime\")\r\n  |> group()\r\n  |> map(fn: (r) => ({ r with dashboard: strings.joinStr(arr: [\r\n      \"<a href=\\\"d/jmeter-results/jmeter-test-results?orgId=1&from=\",\r\n      string(v: int(v: r.startTime)),\"&to=\",\r\n      string(v: int(v: r.endTime)),\"&var-aggregation=60&var-sampleType=transaction&var-runId=\",\r\n      string(v: r.runId),\"&var-testName=\",string(v: r.testName),\"\\\">Dashboard</a>\"\r\n      ], \r\n      v: \"\") }))\r\n  |> keep(columns: [\"runId\", \"testName\", \"dashboard\", \"build\", \"testType\"])\r\n  |> fill(column: \"testType\", value: \"-\")\r\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average response time | Baseline tests | ${testName} | ${testType}",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": " from(bucket: v.bucket)\r\n  |> range(start: 0, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tests\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"avg_tr\")\r\n  |> filter(fn: (r) => r[\"testName\"] == \"${testName}\") \r\n  |> filter(fn: (r) => r[\"testType\"] == \"${testType}\") \r\n  |> toFloat() \r\n  |> keep(columns: [\"runId\", \"_value\", \"_time\"])\r\n  |> group()\r\n  |> sort(columns: [\"_time\"], desc: true)    \r\n  |> limit(n: 10)\r\n  |> sort(columns: [\"_time\"], desc: false)  \r\n"
    }
   ]
  },
  {
   "title": "Median response time | Baseline tests | ${testName} | ${testType}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": " from(bucket: v.bucket)\r\n  |> range(start: 0, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tests\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"median_tr\")\r\n  |> filter(fn: (r) => r[\"testName\"] == \"${testName}\") \r\n  |> filter(fn: (r) => r[\"testType\"] == \"${testType}\") \r\n  |> toFloat() \r\n  |> keep(columns: [\"runId\", \"_value\", \"_time\"])\r\n  |> group()\r\n  |> sort(columns: [\"_time\"], desc: true)    \r\n  |> limit(n: 10)\r\n  |> sort(columns: [\"_time\"], desc: false)  "
    }
   ]
  },
  {
   "title": "90%-tile response time | Baseline tests | ${testName} | ${testType}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": " from(bucket: v.bucket)\r\n  |> range(start: 0, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tests\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"percentile_tr\")\r\n  |> filter(fn: (r) => r[\"testName\"] == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"testType\"] == \"${testType}\")  \r\n  |> toFloat() \r\n  |> keep(columns: [\"runId\", \"_value\", \"_time\"])\r\n  |> group()\r\n  |> sort(columns: [\"_time\"], desc: true)    \r\n  |> limit(n: 10)\r\n  |> sort(columns: [\"_time\"], desc: false)  "
    }
   ]
  }
 ]
}